source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'MiaowShow' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'BarrageRenderer'
pod 'CocoaAsyncSocket'
pod 'LFLiveKit'


end
